# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/vp_switch_final_0/vp_switch_final_0.xci
# IP: The module: 'vp_switch_final_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/vp_switch_final_0/src/rgb2ycbcr_0/rgb2ycbcr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/vp_switch_final_0/src/rgb2ycbcr_0/src/MUL/MUL.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUL || ORIG_REF_NAME==MUL} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/vp_switch_final_0/src/rgb2ycbcr_0/src/ADD/ADD.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD || ORIG_REF_NAME==ADD} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/vp_switch_final_0/src/tresholding_0/tresholding_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tresholding_0 || ORIG_REF_NAME==tresholding_0} -quiet] -quiet

# IP: C:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/vp_switch_final_0/vp_switch_final_0.xci
# IP: The module: 'vp_switch_final_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/vp_switch_final_0/src/rgb2ycbcr_0/rgb2ycbcr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/vp_switch_final_0/src/rgb2ycbcr_0/src/MUL/MUL.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUL || ORIG_REF_NAME==MUL} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/vp_switch_final_0/src/rgb2ycbcr_0/src/ADD/ADD.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD || ORIG_REF_NAME==ADD} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/vp_switch_final_0/src/tresholding_0/tresholding_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tresholding_0 || ORIG_REF_NAME==tresholding_0} -quiet] -quiet
