# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/sr/HyjekDaniel/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/centroid_0/centroid_0.xci
# IP: The module: 'centroid_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsriw/sr/HyjekDaniel/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/centroid_0/src/accum/accum.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accum || ORIG_REF_NAME==accum} -quiet] -quiet

# IP: /home/lsriw/sr/HyjekDaniel/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/centroid_0/src/divider_32_20_0/divider_32_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: /home/lsriw/sr/HyjekDaniel/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/centroid_0/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: /home/lsriw/sr/HyjekDaniel/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/centroid_0/src/divider/divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider || ORIG_REF_NAME==divider} -quiet] -quiet

# IP: /home/lsriw/sr/HyjekDaniel/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/centroid_0/src/divider/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: /home/lsriw/sr/HyjekDaniel/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/centroid_0/centroid_0.xci
# IP: The module: 'centroid_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsriw/sr/HyjekDaniel/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/centroid_0/src/accum/accum.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accum || ORIG_REF_NAME==accum} -quiet] -quiet

# IP: /home/lsriw/sr/HyjekDaniel/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/centroid_0/src/divider_32_20_0/divider_32_20_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: /home/lsriw/sr/HyjekDaniel/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/centroid_0/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: /home/lsriw/sr/HyjekDaniel/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/centroid_0/src/divider/divider.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider || ORIG_REF_NAME==divider} -quiet] -quiet

# IP: /home/lsriw/sr/HyjekDaniel/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/centroid_0/src/divider/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet
