# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/vp_switch_final_0.xci
# IP: The module: 'vp_switch_final_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/rgb2ycbcr_0/rgb2ycbcr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/rgb2ycbcr_0/src/MUL/MUL.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUL || ORIG_REF_NAME==MUL} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/rgb2ycbcr_0/src/ADD/ADD.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD || ORIG_REF_NAME==ADD} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/tresholding_0/tresholding_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tresholding_0 || ORIG_REF_NAME==tresholding_0} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/centroid_0_1/centroid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==centroid_0 || ORIG_REF_NAME==centroid_0} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/centroid_0_1/src/accum/accum.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accum || ORIG_REF_NAME==accum} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/centroid_0_1/src/divider_32_20_0/divider_32_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/centroid_0_1/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/centroid_0_1/src/divider/divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider || ORIG_REF_NAME==divider} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/centroid_0_1/src/divider/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/x_centroid_0/x_centroid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==x_centroid_0 || ORIG_REF_NAME==x_centroid_0} -quiet] -quiet

# IP: C:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/vp_switch_final_0.xci
# IP: The module: 'vp_switch_final_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/rgb2ycbcr_0/rgb2ycbcr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/rgb2ycbcr_0/src/MUL/MUL.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUL || ORIG_REF_NAME==MUL} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/rgb2ycbcr_0/src/ADD/ADD.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD || ORIG_REF_NAME==ADD} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/tresholding_0/tresholding_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tresholding_0 || ORIG_REF_NAME==tresholding_0} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/centroid_0_1/centroid_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==centroid_0 || ORIG_REF_NAME==centroid_0} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/centroid_0_1/src/accum/accum.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accum || ORIG_REF_NAME==accum} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/centroid_0_1/src/divider_32_20_0/divider_32_20_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/centroid_0_1/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/centroid_0_1/src/divider/divider.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider || ORIG_REF_NAME==divider} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/centroid_0_1/src/divider/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test_new/tor_test_new.srcs/sources_1/ip/vp_switch_final_0/src/x_centroid_0/x_centroid_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==x_centroid_0 || ORIG_REF_NAME==x_centroid_0} -quiet] -quiet
