# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/GaliTingus/Documents/SR_Project/REKA/rgb2ycbcr/rgb2ycbcr.srcs/sources_1/ip/MUL/MUL.xci
# IP: The module: 'MUL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/GaliTingus/Documents/SR_Project/REKA/rgb2ycbcr/rgb2ycbcr.srcs/sources_1/ip/MUL/MUL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MUL'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/REKA/rgb2ycbcr/rgb2ycbcr.srcs/sources_1/ip/MUL/MUL.xci
# IP: The module: 'MUL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/GaliTingus/Documents/SR_Project/REKA/rgb2ycbcr/rgb2ycbcr.srcs/sources_1/ip/MUL/MUL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MUL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
