# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/rgb2ycbcr_0_1/rgb2ycbcr_0.xci
# IP: The module: 'rgb2ycbcr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/rgb2ycbcr_0_1/src/MUL/MUL.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUL || ORIG_REF_NAME==MUL} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/rgb2ycbcr_0_1/src/ADD/ADD.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD || ORIG_REF_NAME==ADD} -quiet] -quiet

# IP: C:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/rgb2ycbcr_0_1/rgb2ycbcr_0.xci
# IP: The module: 'rgb2ycbcr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/rgb2ycbcr_0_1/src/MUL/MUL.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUL || ORIG_REF_NAME==MUL} -quiet] -quiet

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_test/tor_test.srcs/sources_1/ip/rgb2ycbcr_0_1/src/ADD/ADD.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD || ORIG_REF_NAME==ADD} -quiet] -quiet
