# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_bin/tor_bin.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_bin/tor_bin.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/LUT/LUT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LUT || ORIG_REF_NAME==LUT} -quiet] -quiet

# XDC: c:/Users/GaliTingus/Documents/SR_Project/tor_bin/tor_bin.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/LUT/LUT_ooc.xdc

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_bin/tor_bin.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/GaliTingus/Documents/SR_Project/tor_bin/tor_bin.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/LUT/LUT.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LUT || ORIG_REF_NAME==LUT} -quiet] -quiet

# XDC: c:/Users/GaliTingus/Documents/SR_Project/tor_bin/tor_bin.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/src/LUT/LUT_ooc.xdc
